# Generated by Django 4.0.3 on 2022-04-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_bgameuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgameuser',
            name='is_active',
        ),
    ]
