# Generated by Django 4.0.3 on 2022-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_bgameuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgameuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
