# Generated by Django 4.0.3 on 2022-04-09 13:00

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_profile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='profile', validators=[common.validators.ValidateFileMaxSizeInMb(5)]),
        ),
    ]
