# Generated by Django 4.0.3 on 2022-04-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgameuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
