# Generated by Django 4.0.3 on 2022-04-09 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgameuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\_]*$', 'Ensure this value contains only letters, numbers, and underscore.'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
