# Generated by Django 4.0.3 on 2022-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_bgameuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
