# Generated by Django 4.0.3 on 2022-04-14 08:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
