# Generated by Django 4.0.3 on 2022-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default='2022-1-1'),
            preserve_default=False,
        ),
    ]
