# Generated by Django 4.0.3 on 2022-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0004_game_is_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_released',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('Coming Soon', 'Coming Soon')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
