# Generated by Django 4.0.3 on 2022-04-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0006_game_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games_rental.game'),
            preserve_default=False,
        ),
    ]
