# Generated by Django 4.0.3 on 2022-04-08 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0012_customergamerental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergamerental',
            name='return_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
    ]
