# Generated by Django 4.0.3 on 2022-04-08 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_rental', '0013_alter_customergamerental_return_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerGameRental',
            new_name='CustomerGameRent',
        ),
    ]
