# Generated by Django 4.0.3 on 2022-04-08 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0014_rename_customergamerental_customergamerent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergamerent',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
    ]
