# Generated by Django 4.0.3 on 2022-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0019_customergamerent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergamerent',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
