# Generated by Django 4.0.3 on 2022-04-08 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_rental', '0021_alter_customergamerent_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergamerent',
            old_name='start_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='customergamerent',
            unique_together={('game', 'user')},
        ),
    ]
