# Generated by Django 4.0.3 on 2022-04-08 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_rental', '0023_alter_customergamerent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customergamerent',
            unique_together={('game', 'user')},
        ),
    ]
