# Generated by Django 4.0.3 on 2022-04-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0024_alter_customergamerent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customergamerent',
            unique_together=set(),
        ),
    ]
