# Generated by Django 4.0.3 on 2022-04-09 12:58

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0025_alter_customergamerent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slidebar', validators=[common.validators.ValidateFileMaxSizeInMb(7)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_rental.game')),
            ],
        ),
    ]
