# Generated by Django 4.0.3 on 2022-04-10 16:27

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0031_remove_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider', validators=[common.validators.ValidateFileMaxSizeInMb(7)]),
        ),
    ]
