# Generated by Django 4.0.3 on 2022-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0032_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
