# Generated by Django 4.0.3 on 2022-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0005_remove_game_is_released_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-4-4'),
            preserve_default=False,
        ),
    ]
