# Generated by Django 4.0.3 on 2022-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0007_review_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
