# Generated by Django 4.0.3 on 2022-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0009_rename_price_game_rent_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rent_price',
            new_name='rent_price_per_month',
        ),
    ]
