# Generated by Django 4.0.3 on 2022-04-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0010_rename_rent_price_game_rent_price_per_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rent_price_per_month',
            new_name='rent_price_per_day',
        ),
    ]
