# Generated by Django 4.0.3 on 2022-04-08 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0016_alter_customergamerent_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergamerent',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 16, 4, 42, 619441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customergamerent',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 16, 4, 42, 619424, tzinfo=utc)),
        ),
    ]
