# Generated by Django 4.0.3 on 2022-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0018_alter_customergamerent_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergamerent',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
