# Generated by Django 4.0.3 on 2022-04-08 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0020_alter_customergamerent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergamerent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
