# Generated by Django 4.0.3 on 2022-04-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0022_rename_start_date_customergamerent_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customergamerent',
            unique_together=set(),
        ),
    ]
