# Generated by Django 4.0.3 on 2022-04-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental', '0030_rename_slidebar_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
